INSERT INTO Service (name, description, duration, price) VALUES
('Extension Fixed', '', '00:45', 0.00),
('Extension Installation', '', '00:45', 200.00),
('Extensions New Set', '', '00:45', 450.00),
('Extension Removal', 'Just the removal of extensions, prices varies based on the type of extensions. If you are unsure, contact the salon about time and estimate on removal process or about additional add-ons.', '00:45', 80.00),
('Extension Move-up', 'Only applies to pre-existing extensions on hair that needs a move-up maintenance. Please contact the salon about what type of extension you have for us to book accordingly, or if you need new extensions.', '00:45', 200.00),
('Women''s Haircut', 'Prices may vary based on client''s hair length, density, and texture. Includes a wash and blow dry.', '00:45', 60.00),
('Men''s Haircut', 'Price varies based on client''s hair density, length, and texture. Includes a wash and style.', '00:45', 45.00),
('Kid''s Haircut', '', '00:45', 35.00),
('Color/ Cut/ Partial Highlight', '', '00:45', 185.00),
('Color/Cut/Full Highlight', '', '00:45', 215.00),
('Color Touch up', '', '00:45', 85.00),
('Color & Cut', '', '00:45', 135.00),
('Color Correction', 'Please call the salon to book this appointment. Any service that entails a major transformation to your existing hair.', '00:45', 250.00),
('Ombre/Balayage', '', '00:45', 185.00),
('Ombre/Balayage & Haircut', '', '00:45', 230.00),
('On-Scalp Lightener', '', '00:45', 125.00),
('Partial Highlight & Haircut', '', '00:45', 165.00),
('Partial Highlight', '', '00:45', 110.00),
('Baby Color', '', '00:45', 0.00),
('Shampoo & Blowout', '', '00:45', 55.00),
('Updo', '', '00:45', 90.00),
('Deep Conditioning Treatment', '', '00:45', 55.00),
('Splitend Mender', '', '00:45', 70.00),
('Bang Trim', '', '00:45', 15.00),
('Base Bump', '', '00:45', 55.00),
('Bleach Wash', '', '00:45', 65.00),
('Brazilian Blowout', 'A Smoothing Treatment that lives in the hair, lasting from 8-12 weeks. Cuts styling time in half. Solution used is the Brazilian Blowout brand. (Prices varies based on client''s hair density, texture, and length. Starting price is based from 2" past the shoulders for the Brazilian Blowout. Anything past it will be additional to the starting price for the treatment.)', '00:45', 0.00),
('Brazilian Blowout w/ Haircut', 'A Smoothing Treatment that lives in the hair, lasting from 8-12 weeks. Cuts styling time in half. Solution used is the Brazilian Blowout brand. (Prices varies based on client''s hair density, texture, and length. Starting price is based from 2" past the shoulders for the Brazilian Blowout. Anything past it will be additional to the starting price for the treatment.)', '00:45', 360.00),
('Brazilian Blowout Express', 'A Smoothing Treatment that lives in the hair, lasting up to 4 weeks. Cuts styling time in half. Solution used is the Brazilian Blowout brand. (Prices varies based on client''s hair density, texture, and length. Starting price is based from 2" past the shoulders for the Brazilian Blowout. Anything past it will be additional to the starting price for the treatment.)', '00:45', 0.00),
('Color Consultation', '15-30min free in-person consultation with a Hairstylist', '00:45', 0.00),
('Extension Consultation', 'Free 15-30 mins in-person consultation for hair extensions. If you have any questions, please contact our salon.', '00:45', 0.00),
('Platinum Card Foils', '', '00:45', 200.00);
